#!/usr/bin/env bash
# Bash script that displays "Best School" 10 times using until loop

i=1
until ((i>10))  # Loop runs until i becomes greater than 10
do
    echo "Best School"  # Print "Best School"
    ((i++))  # Increment i
done
